revolv/ambassador/urls.py
from django.conf.urls import patterns, url
from revolv.ambassador.views import AmbassadorDashboardView
from revolv.base.users import is_ambassador

urlpatterns = patterns(
    '',
    url(r'^$', is_ambassador(AmbassadorDashboardView.as_view()), name='dashboard'),
)

revolv/donor/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required
from revolv.donor.views import DonorDashboardView, AccountingView, AccountingPartialView

urlpatterns = patterns(
    '',
    url(r'^$', login_required(DonorDashboardView.as_view()), name='dashboard'),
    url(r'^accounting$', AccountingView.as_view(), name='accounting'),
    url(r'^accounting/partial$', AccountingPartialView.as_view(), name='accountingPartial')
)

revolv/project/urls.py
from django.conf.urls import patterns, url
from revolv.base.users import is_ambassador, is_logged_in
from revolv.project.views import (CreateProjectView, EditProjectUpdateView,
                                  PostProjectUpdateView, ProjectView,
                                  ReviewProjectView, SubmitDonationView,
                                  UpdateProjectView, ProjectListReinvestmentView,
                                  stripe_payment)

urlpatterns = patterns(
    '',
    url(r'^create$', is_ambassador(CreateProjectView.as_view()), name='new'),
    url(r'^(?P<pk>\d+)/stripe/$', stripe_payment, name='stripe_payment'),
    url(r'^(?P<pk>\d+)/edit$', is_ambassador(UpdateProjectView.as_view()), name='edit'),
    url(r'^(?P<pk>\d+)/$', ProjectView.as_view(), name='view'),
    url(r'^(?P<pk>\d+)/reinvest/$', 'revolv.project.views.reinvest', name='reinvest'),
    url(r'^(?P<pk>\d+)/review$', is_ambassador(ReviewProjectView.as_view()), name='review'),
    url(r'reinvest_list/$', is_logged_in(ProjectListReinvestmentView.as_view()), name='reinvest_list'),
    url(r'^(?P<pk>\d+)/donation/submit$', SubmitDonationView.as_view(), name="donation_submit"),
    url(r'^(?P<pk>\d+)/update$', is_ambassador(PostProjectUpdateView.as_view()), name='update'),
    url(r'^editupdate/(?P<pk>\d+)$', is_ambassador(EditProjectUpdateView.as_view()), name='edit_project_update'),
)

revolv/urls.py
from django.conf.urls import include, patterns, url
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static

from wagtail.wagtailadmin import urls as wagtailadmin_urls
from wagtail.wagtailcore import urls as wagtail_urls
from wagtail.wagtaildocs import urls as wagtaildocs_urls

from revolv.base import views as base_views

urlpatterns = patterns(
    '',
    (r'^ckeditor/', include('ckeditor.urls')),  # for assets for the ckedit widget, etc
    url(r'^facebook/', include('django_facebook.urls')),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^$', base_views.HomePageView.as_view(), name='home'),
    url(r'^project/', include('revolv.project.urls', namespace='project')),
    url(r'^my-portfolio/$', base_views.DashboardRedirect.as_view(), name='dashboard'),
    url(r'^my-portfolio/categories/$', base_views.CategoryPreferenceSetterView.as_view(), name='dashboard_category_setter'),
    url(r'^my-portfolio/admin/', include('revolv.administrator.urls', namespace='administrator')),
    url(r'^my-portfolio/ambassador/', include('revolv.ambassador.urls', namespace='ambassador')),
    url(r'^my-portfolio/donor/', include('revolv.donor.urls', namespace='donor')),

    url(r'^what-we-do/projects/', base_views.ProjectListView.as_view(), name='projects_list'),
    url(r'^signin/$', base_views.SignInView.as_view(), name='signin'),
    url(r'^login/$', base_views.LoginView.as_view(), name='login'),
    url(r'^signup/$', base_views.SignupView.as_view(), name='signup'),
    url(r'^logout/$', base_views.LogoutView.as_view(), name='logout'),
    url(r'^unsubscribe/(?P<action>\w+)/$', 'revolv.base.views.unsubscribe', name='unsubscribe'),
    url(r'^my_social_account/$', 'revolv.base.views.social_connection', name='social-connection'),
    url(r'^social_connect_failed/$', 'revolv.base.views.social_exception', name='social-exception'),

    url(r'^password_reset/$', base_views.password_reset_initial, name="password_reset"),
    url(r'^password_reset/done/$', base_views.password_reset_done, name="password_reset_done"),
    url(r'^password_reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$$', base_views.password_reset_confirm, name="password_reset_confirm"),
    url(r'^password_reset/complete/$', base_views.password_reset_complete, name="password_reset_complete"),
    url(r'^password_change/$', base_views.password_change, name="password_change"),

    # wagtail urls, see http://wagtail.readthedocs.org/en/v1.0b2/howto/settings.html
    # note: we're not including the search module for public users, so we don't define it here
    url(r'^cms/', include(wagtailadmin_urls)),
    url(r'^documents/', include(wagtaildocs_urls)),
    url(r'social/', include('social.apps.django_app.urls', namespace='social')),
    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's serving mechanism

    url(r'', include(wagtail_urls)),

) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

revolv/project/models.py
import datetime
from itertools import chain

from ckeditor.fields import RichTextField
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models import Q, Sum
from imagekit.models import ImageSpecField, ProcessedImageField
from imagekit.processors import ResizeToFill
from revolv.base.models import RevolvUserProfile
from revolv.lib.utils import ImportProxy
from revolv.payments.models import Payment, PaymentType
from revolv.project.stats import KilowattStatsAggregator


class ProjectManager(models.Manager):
    """
    Manager for running custom operations on the Projects.
    """

    def get_featured(self, num_projects, queryset=None):
        """ Get num_projects amount of active projects. If we don't have
        enough active projects, then we retrieve completed projects. This
        function may return fewer projects than requested if not enough exist.

        :num_projects: Number of projects to be retrieved
        :queryset: The queryset in which to search for projects
        :return: A list of featured project objects
        """
        if queryset is None:
            queryset = super(ProjectManager, self).get_queryset()
        featured_projects = queryset.filter(
            project_status=Project.ACTIVE).order_by(
            'end_date')[:num_projects]
        if featured_projects.count() < num_projects:
            num_completed_needed = num_projects - featured_projects.count()
            completed_projects = queryset.filter(
                project_status=Project.COMPLETED).order_by(
                'end_date')[:num_completed_needed]
            return list(chain(featured_projects, completed_projects))
        else:
            return featured_projects

    def get_completed(self, queryset=None):
        """ Gets all the projects that have been completed funding.

        :queryset: The queryset in which to search for projects
        :return: A list of completed project objects
        """
        if queryset is None:
            queryset = super(ProjectManager, self).get_queryset()
        completed_projects = queryset.filter(
            project_status=Project.COMPLETED
        ).order_by('end_date')
        return completed_projects

    def get_active(self, queryset=None):
        """ Gets all the projects that have been active to go into funding.

        :queryset: The queryset in which to search for projects
        :return: A list of active project objects
        """
        if queryset is None:
            queryset = super(ProjectManager, self).get_queryset()
        active_projects = queryset.filter(
            project_status=Project.ACTIVE
        ).order_by('end_date')
        return active_projects

    def get_proposed(self, queryset=None):
        """ Gets all the projects that are currently in review (proposed).

        :queryset: The queryset in which to search for projects
        :return: A list of in review project objects
        """
        if queryset is None:
            queryset = super(ProjectManager, self).get_queryset()
        proposed_projects = queryset.filter(
            project_status=Project.PROPOSED
        ).order_by('updated_at')
        return proposed_projects

    def get_drafted(self, queryset=None):
        """ Get all the projects that are drafted in the queryset.

        :queryset: The queryset in which to search for projects
        :return: A list of in review project objects
        """
        if queryset is None:
            queryset = super(ProjectManager, self).get_queryset()
        drafted_projects = queryset.filter(
            project_status=Project.DRAFTED
        ).order_by('updated_at')
        return drafted_projects

    def get_staged(self, queryset=None):
        """ Get all the projects that are staged in the queryset.

        :queryset: The queryset in which to search for projects
        :return: A list of in review project objects
        """
        if queryset is None:
            queryset = super(ProjectManager, self).get_queryset()
        staged_projects = queryset.filter(
            project_status=Project.STAGED
        ).order_by('updated_at')
        return staged_projects

    def statistics(self, queryset=None):
        """
        Return a revolv.project.stats.KilowattStatsAggregator to
        aggregate statistics about the impact of the given queryset of
        projects.
        """
        if queryset is None:
            queryset = super(ProjectManager, self).get_queryset()
        return KilowattStatsAggregator.from_project_queryset(queryset)

    def owned_projects(self, user_profile):
        """ Get all projects owned by a RevolvUserProfile.

        :user: The user of interest
        :return: A list of projects for which user's RevolvUserProfile
        is the ambassador or creator.
        """
        return Project.objects.filter(Q(ambassador=user_profile) | Q(created_by_user=user_profile))

    def donated_projects(self, user_profile):
        """
        :return: Projects to which this RevolvUserProfile has donated
        """
        return user_profile.project_set.all()

    def create_from_form(self, form, creator):
        """ Creates project from form and sets created_by_user to a RevolvUserProfile.

        :form: The form
        :creator: The RevolvUserProfile of the creator of the project
        :return: Project created and saved
        """
        project = form.save(commit=False)
        project.created_by_user = creator
        project.save()
        return project

    def get_eligible_projects_for_reinvestment(self, queryset=None):
        """
        :return list(queryset) of eligible project to receive reinvestement
        """
        return self.get_active(queryset).filter(monthly_reinvestment_cap__gt=0.0)

    def get_completed_unpaid_off_projects(self, queryset=None):
        """
        :return list(queryset) of completes project which do monthly repayment.
        """
        return self.get_completed(queryset).filter(is_paid_off=True)


class Project(models.Model):
    """
    Project model. Stores basic metadata, information about the project,
    donations, energy impact, goals, and info about the organization.

    Note about project statuses: there are five kinds of statuses that a
    project can have, and we show projects to different users in different
    ways based on their status.

    When an ambassador or admin first creates a project, it becomes DRAFTED,
    which means that it's a draft and can be edited, but is not in a complete
    state yet (description may need editing, etc). Eventualy the ambassador
    can propose the project for review from the admins, at which time it becomes
    PROPOSED. A proposed project is viewable by admins in their dashboard, as
    well as by the ambassadors that created it.

    When an admin approves a project, it becomes STAGED, which means it is ready
    to go but is not active yet, and as such is not viewable by the public. Staged
    projects are also visible to all admins in their dashboards. When it's time
    for the project to go live and start accepting donations, the admin can mark
    it as ACTIVE, which means it will actually be public and people can donate to
    it. When a project is done, the admin can mark it as COMPLETED, at which point
    it will stop accepting donations and start using repayments.
    """
    ACTIVE = 'AC'
    STAGED = 'ST'
    PROPOSED = 'PR'
    COMPLETED = 'CO'
    DRAFTED = 'DR'
    PROJECT_STATUS_CHOICES = (
        (ACTIVE, 'Active'),
        (STAGED, 'Staged'),
        (PROPOSED, 'Proposed'),
        (COMPLETED, 'Completed'),
        (DRAFTED, 'Drafted'),
    )
    LESS_THAN_ONE_DAY_LEFT_STATEMENT = "only hours left"
    NO_DAYS_LEFT_STATEMENT = "deadline reached"

    funding_goal = models.DecimalField(
        max_digits=15,
        decimal_places=2,
        help_text='How much do you aim to raise for this project?'
    )
    title = models.CharField(
        max_length=255,
        help_text='How would you like to title this project?'
    )
    tagline = models.CharField(
        max_length=100,
        null=True,
        blank=False,
        help_text='Select a short tag line that describes this project. (No more than 100 characters.)'
    )
    video_url = models.URLField(
        'Video URL',
        max_length=255,
        blank=False,
        help_text='Link to a Youtube video about the project or community.',
    )
    # power output of array in kilowatts
    impact_power = models.FloatField(
        'Expected Killowatt Output',
        help_text='What is the expected output in killowatts of the proposed solar array?'
    )
    # solar log graphics url
    solar_url = models.URLField(
        'Solar Log Graphics URL',
        max_length=255,
        blank=True,
        help_text='This can be found by going to http://home.solarlog-web.net/, going to the \
        solar log profile for your site, and clicking on the Graphics sub-page. Copy and paste \
        the URL in the address bar into here.'
    )
    location = models.CharField(
        'Organization Address',
        max_length=255,
        help_text='What is the address of the organization where the solar panels will be installed?'
    )
    # latitude and longitude of the organization location
    location_latitude = models.DecimalField(
        max_digits=17,
        decimal_places=14,
        default=0.0
    )
    location_longitude = models.DecimalField(
        max_digits=17,
        decimal_places=14,
        default=0.0
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    end_date = models.DateField(
        help_text='When will this crowdfunding project end?'
    )
    # the start date of a project is whenever the project becomes live,
    # so we have to set it dynamically. Accordingly, the start_date
    # field is blank=True.
    start_date = models.DateField(
        blank=True,

revolv/administrator/forms.py
from django import forms
from revolv.payments.models import AdminAdjustment
from revolv.project.models import Project
from django.forms.models import modelform_factory


AdjustmentForm = modelform_factory(AdminAdjustment)

revolv/administrator/views.py
import csv

from django.http import HttpResponse
from django.views.generic import TemplateView
from revolv.base.models import RevolvUserProfile
from revolv.base.users import UserDataMixin
from revolv.base.utils import ProjectGroup
from revolv.base.views import BaseStaffDashboardView
from revolv.project.models import Project


class AdministratorDashboardView(BaseStaffDashboardView):
    """
    Basic view for the Administrator dashboard. Shows the list of projects that this
    ambassador owns. Also, shows drafted projects.
    """
    template_name = 'base/dashboard.html'
    role = "admin"

    def get_context_data(self, **kwargs):
        context = super(AdministratorDashboardView, self).get_context_data(**kwargs)

        context["project_dict"][ProjectGroup('Drafted Projects', "drafted")] = Project.objects.get_drafted()
        return context


class AdministratorEmailView(UserDataMixin, TemplateView):
    """View for the list of newsletter subscribers for the dashboard.
    """
    template_name = 'administrator/email.html'

    def get_context_data(self, **kwargs):
        context = super(AdministratorEmailView, self).get_context_data(**kwargs)

        user_profiles = RevolvUserProfile.objects.get_subscribed_to_newsletter()
        user_emails = list(user_profiles.values_list("user__email", flat=True))

        context['subscribed_user_emails'] = user_emails
        return context


def admin_email_csv_download(request):
    """View for downloading the list of newsletter subscribers as a csv file.
    Accessed via AdministratorEmailView.
    """
    # Create the HttpResponse object with the appropriate CSV header.
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="emails.csv"'

    users_subscribed = RevolvUserProfile.objects.get_subscribed_to_newsletter()
    newsletter_rows = [(u.user.email, u.user.first_name, u.user.last_name, u.user.date_joined) for u in users_subscribed]

    writer = csv.writer(response)
    writer.writerow(['Email', 'FirstName', 'LastName', 'DateJoined'])
    writer.writerows(newsletter_rows)

    return response

revolv/revolv_cms/views.py
from django.shortcuts import render

# Create your views here.

revolv/templates/base/partials/dashboard_project_header.html
{% comment %}
    Dashboard Project Header

    This partial is the header that is displayed on each project on the RE-volv dashboard.
    See dashboard_project.html for more documentation.
{% endcomment %}
<div class="dashboard-project-header row">
    <div class="title-area large-6 medium-5 columns">
        <div class="sidebar-toggle sidebar-toggle-open"><i class="fa fa-align-justify"></i></div>
        <div class="project-header-inner-wrap">
            <div class="title-line">
                <div class="title"><a href="{% url "project:view" project.pk %}">{{project.title}}</a></div>
                <div class="project-status project-status-large">({{project.status_display}})</div>
            </div>
            <div class="project-status project-status-medium">({{project.status_display}})</div>
            <div class="location">
                <i class="fa fa-map-marker"></i><span class="location-text">{{project.location_city_state_zip}}</span>
            </div>
        </div>
    </div>
    <div class="controls controls-large large-6 medium-7 columns">
        {% include "base/partials/project_controls.html" with project=project profile=user.revolvuserprofile %}
    </div>
</div>
<!-- controls-small will be shown on mobile devices, in place of controls-large -->
<div class="row controls-small">
    <div class="controls small-12 columns">
        {% include "base/partials/project_controls.html" with project=project profile=user.revolvuserprofile %}
    </div>
</div>

revolv/templates/base/partials/dashboard_sidebar.html
{% comment %}
    Dashboard Sidebar

    This is a partial for the sidebar of the RE-volv dashboard design (mockup can be seen at
    https://cloud.githubusercontent.com/assets/7706852/6608266/b4c8fdd8-c802-11e4-9610-939a5f9f5dd9.png).
    This partial accepts the following template variables:

    :user: the currently logged in user. The user will always be logged in, since if they're
            seeing this page then they have bypassed the functionality which redirects to the
            homepage for unauthenticated users.

    :project_dict: a dictionary with keys as revolv.base.utils.ProjectGroups, and values as lists
        of project model objects in the group. The project group names have a `key` and a `display`:
        the key should be used for uniquely identifying the project group in class names, etc, and the
        display should be used for the sidebar heading (e.g. "Proposed Projects").

    The idea for the sidebar is that there is an area at the top where the user can switch between
    different user types, if applicable, can see the projects which are relevant to their role, and can also
    see management pages (for example admin accounting page) below. The point of this template is to
    conditionally render all of these partials and things based on what type of user the current user is.
{% endcomment %}
{% spaceless %}
<div class="sidebar-close-button sidebar-toggle-close"><i class="fa fa-close"></i></div>
<div class="role-select">
    {% if role == "administrator" and user.revolvuserprofile.is_administrator %}
        <div class="role-select-inner">administrator</div>
    {% elif role == "ambassador" and user.revolvuserprofile.is_ambassador %}
        <div class="role-select-inner">ambassador</div>
    {% else %}
        <div class="role-select-inner">{{user.username}}</div>
    {% endif %}
    {% if user.revolvuserprofile.is_ambassador %}
        <div class="dashboard-sidebar-chevron" data-state="collapsed"><i class="fa fa-chevron-down"></i></div>
    {% endif %}
</div>
{% if user.revolvuserprofile.is_ambassador %}
<div class="role-select-options">
    <div class="dashboard-header">View as:</div>
    {% if user.revolvuserprofile.is_administrator %}
        <div class="role-select-option"><a href="/dashboard/admin/">administrator</a></div>
    {% endif %}
    <div class="role-select-option"><a href="/dashboard/ambassador/">ambassador</a></div>
    <div class="role-select-option"><a href="/dashboard/donor/">donor</a></div>
</div>
{% endif %}

{% if user.revolvuserprofile.is_ambassador and role != "donor" %}
<div class="dashboard-section create-new">
    <a href="{% url "project:new" %}" class="create-new-button" id="create_project">Create Project</a>
</div>
{% endif %}
<div class="dashboard-section projects">
    {% if donor_has_no_donated_projects %}
        <div class="dashboard-header">No projects found.</div>
    {% else %}
        {% for project_group, project_list in project_dict.items %}
            <div class="dashboard-header">{{ project_group.display }}</div>
            {% with outer_counter=forloop.counter %}
                {% for project in project_list %}
                    <div class="dashboard-sidebar-project-container dashboard-sidebar-project-container-{{project.pk}} dashboard-data-link" data-section="project-{{project.pk}}">
                        <div class="dashboard-sidebar-bullet-point {{project_group.key}}"></div>
                        <div class="dashboard-sidebar-project project-{{project.pk}} project-status-{{project.pk}}-{{project.project_status}} {{project_group.key}} dashboard-data-link">{{project.title}}</div>
                    </div>
                {% endfor %}
            {% endwith %}
        {% endfor %}
    {% endif %}
</div>
<div class="dashboard-section manage">
    <div class="dashboard-header">Manage</div>
    <div class="dashboard-manage-link my-impact-and-category-preferences"><a id="my_impact" href="{% url "dashboard" %}">My Impact</a></div>
    <div class="dashboard-manage-link"><a id="change_password_link" href="/password_change/">Change Password</a></div>
    <div class="dashboard-manage-link"><a id="logout_link" href="/logout/">Logout</a></div>
</div>
{% endspaceless %}

revolv/templates/base/partials/list_projects.html
{% load static humanize %}

<div class="active-projects-module animated embedded">
  <div class="container">
    <div class="row">
      {% for active_project in active_projects %}
      <div class="col-md-4">
        <div class="module-box">
          <div class="img-main">
            <a href="{% url "project:view" pk=active_project.pk %}" class="img-link">
              <span class="txt-table">
                <span class="txt">
                    {{ active_project.title }}
                </span>
              </span>
              <div class="img" style="background-image:url({% static 'images/solar-panels.jpg' %})"></div>
            </a>
            <div class="funded-round">
              <div class="status-circular">
                <span class="status-text">
                  <span class="round-depict"><span>OF</span> ${{ active_project.funding_goal|floatformat:0|intcomma }}</span>
                </span>
                <!-- end .status-text -->
                <div class="status-indicator desktop-circle">
                  <input type="text" value="{{ active_project.percent_complete }}" data-min="0" data-width="105" data-height="105" data-bgcolor="#fff" data-fgcolor="#14b1e7" data-max="100" data-readonly="true" data-thickness=".24">
                </div>
                <div class="status-indicator small-circle">
                  <input type="text" value="{{ active_project.percent_complete }}" data-min="0" data-width="92" data-height="92" data-bgcolor="#fff" data-fgcolor="#14b1e7" data-max="100" data-readonly="true" data-thickness=".2">
                </div>
                <div class="status-indicator tablet-circle">
                  <input type="text" value="{{ active_project.percent_complete }}" data-min="0" data-width="200" data-height="200" data-bgcolor="#fff" data-fgcolor="#14b1e7" data-max="100" data-readonly="true" data-thickness=".12">
                </div>
                <div class="status-indicator mobile-circle">
                  <input type="text" value="{{ active_project.percent_complete }}" data-min="0" data-width="98" data-height="98" data-bgcolor="#fff" data-fgcolor="#14b1e7" data-max="100" data-readonly="true" data-thickness=".12">
                </div>
              </div>
            </div>
          </div>
          <!-- end .img-main -->
          <div class="info-main">
            <div class="blue-bar">
              <span class="pull-left">${{ active_project.amount_donated|floatformat:"0"|intcomma }}</span>
              <span class="pull-right">{{ active_project.days_left }} Days Left</span>
            </div>
            <!-- end .blue-bar -->
            <div class="dark-blue-bar">
              <span class="pull-left actual-energy">{{ active_project.actual_energy }} lbs CO<sub>2</sub></span>
              <span class="pull-right">{{ active_project.donors.count }} Donors</span>
            </div>
            <!-- end .blue-bar -->
          </div>
          <!-- end .info-main -->
        </div>
        <!-- end .module-box -->
      </div>
      {% endfor %}
    </div>
  </div>
 </div>

revolv/templates/base/partials/project-nav.html
{% extends "base/partials/nav.html" %}

{% block "header-classes" %}edit-project-header{% endblock "header-classes" %}

{% block "extra-header" %}
  {% if project.id %}
    <h1>Edit Project</h1>
  {% else %}
    <h1>Create Project</h1>
  {% endif %}
{% endblock %}

revolv/templates/base/partials/project_controls.html
{% comment %}
    Project Controls

    This template renders a series of forms (for the RE-volv dashboard page) based
    on a given project and what kind of user is logged in. For example: when an
    ambassador is logged in, we want to render controls for editing and proposing
    projects, whereas an admin can do other things like mark them as complete. Note
    that if the logged in user is neither an admin nor an ambassador this template
    will simply render nothing.

    This template expects to be rendered with the following context:

    :project: the project in question.
    :profile: the RevolvUserProfile (base/models.py) representing the currently logged
        user.
{% endcomment %}
{% spaceless %}
{% if project and profile %}
    {% if profile.is_administrator %}
        {% if project.is_drafted %}
            <form id="propose_form_{{project.pk}}" enctype="multipart/form-data" method="POST" action="{% url "project:review" pk=project.id %}">
                {% csrf_token %}
                <input id="propose_project" class="small button" name="_propose" type="submit" value="Propose" />
            </form>
        {% endif %}
        {% if project.is_proposed %}
            <form id="stage_deny_form_{{project.pk}}" enctype="multipart/form-data" method="POST" action="{% url "project:review" pk=project.id %}">
                {% csrf_token %}
                <input id="stage_project" class="small button success" name="_stage" type="submit" value="Approve" />
                <input id="deny_project" class="small button alert" name="_deny" type="submit" value="Deny" />
            </form>
        {% endif %}
        {% if project.is_staged %}
            <form id="approve_form_{{project.pk}}" enctype="multipart/form-data" method="POST" action="{% url "project:review" pk=project.id %}">
                {% csrf_token %}
                <input id="approve_project" class="small button success" name="_approve" type="submit" value="Start campaign" />
            </form>
        {% endif %}
        {% if project.is_active %}
            <form id="complete_form_{{project.pk}}" enctype="multipart/form-data" method="POST" action="{% url "project:review" pk=project.id %}">
                {% csrf_token %}
                <input id="complete_project" class="small button success" name="_complete" type="submit" value="Complete" />
                <input id="stage_project" class="small button alert" name="_unapprove" type="submit" value="Pause campaign" />
            </form>
        {% endif %}
        {% if project.is_completed or project.is_active %}
            <form id="post_project_updates_form_{{project.pk}}" enctype="multipart/form-data" method="GET" action="{% url "project:update" pk=project.id %}">
                <input id="post_project_updates" class="small button" type="submit" value="Post Updates" />
            </form>
        {% endif %}
        {% if project.is_completed %}
            <form id="incomplete_form_{{project.pk}}" enctype="multipart/form-data" method="POST" action="{% url "project:review" pk=project.id %}">
                {% csrf_token %}
                <input id="incomplete_project" class="small button alert" name="_incomplete" type="submit" value="Mark as Incomplete" />
            </form>
        {% endif %}
        <form id="edit_form_{{project.pk}}" enctype="multipart/form-data" method="GET" action="{% url "project:edit" pk=project.id %}">
            <input id="edit_project" class="small button" type="submit" value="Edit" />
        </form>
    {% elif profile.is_ambassador %}
        {% if project.is_drafted %}
            <form id="propose_form_{{project.pk}}" enctype="multipart/form-data" method="POST" action="{% url "project:review" pk=project.id %}">
                {% csrf_token %}
                <input id="propose_project" class="small button" name="_propose" type="submit" value="Propose" />
            </form>
            <form id="edit_form_{{project.pk}}" enctype="multipart/form-data" method="GET" action="{% url "project:edit" pk=project.id %}">
                <input id="edit_project" class="small button" type="submit" value="Edit" />
            </form>
        {% endif %}
        {% if project.is_completed or project.is_active %}
            <form id="post_project_updates_form_{{project.pk}}" enctype="multipart/form-data" method="GET" action="{% url "project:update" pk=project.id %}">
                <input id="post_project_updates" class="small button" type="submit" value="Post Updates" />
            </form>
        {% endif %}
    {% endif %}
{% endif %}
{% endspaceless %}