revolv/ambassador/urls.py
from django.conf.urls import patterns, url
from revolv.ambassador.views import AmbassadorDashboardView
from revolv.base.users import is_ambassador

urlpatterns = patterns(
    '',
    url(r'^$', is_ambassador(AmbassadorDashboardView.as_view()), name='dashboard'),
)

revolv/donor/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required
from revolv.donor.views import DonorDashboardView, AccountingView, AccountingPartialView

urlpatterns = patterns(
    '',
    url(r'^$', login_required(DonorDashboardView.as_view()), name='dashboard'),
    url(r'^accounting$', AccountingView.as_view(), name='accounting'),
    url(r'^accounting/partial$', AccountingPartialView.as_view(), name='accountingPartial')
)

revolv/project/urls.py
from django.conf.urls import patterns, url
from revolv.base.users import is_ambassador, is_logged_in
from revolv.project.views import (CreateProjectView, EditProjectUpdateView,
                                  PostProjectUpdateView, ProjectView,
                                  ReviewProjectView, SubmitDonationView,
                                  UpdateProjectView, ProjectListReinvestmentView,
                                  stripe_payment)

urlpatterns = patterns(
    '',
    url(r'^create$', is_ambassador(CreateProjectView.as_view()), name='new'),
    url(r'^(?P<pk>\d+)/stripe/$', stripe_payment, name='stripe_payment'),
    url(r'^(?P<pk>\d+)/edit$', is_ambassador(UpdateProjectView.as_view()), name='edit'),
    url(r'^(?P<pk>\d+)/$', ProjectView.as_view(), name='view'),
    url(r'^(?P<pk>\d+)/reinvest/$', 'revolv.project.views.reinvest', name='reinvest'),
    url(r'^(?P<pk>\d+)/review$', is_ambassador(ReviewProjectView.as_view()), name='review'),
    url(r'reinvest_list/$', is_logged_in(ProjectListReinvestmentView.as_view()), name='reinvest_list'),
    url(r'^(?P<pk>\d+)/donation/submit$', SubmitDonationView.as_view(), name="donation_submit"),
    url(r'^(?P<pk>\d+)/update$', is_ambassador(PostProjectUpdateView.as_view()), name='update'),
    url(r'^editupdate/(?P<pk>\d+)$', is_ambassador(EditProjectUpdateView.as_view()), name='edit_project_update'),
)

revolv/urls.py
from django.conf.urls import include, patterns, url
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static

from wagtail.wagtailadmin import urls as wagtailadmin_urls
from wagtail.wagtailcore import urls as wagtail_urls
from wagtail.wagtaildocs import urls as wagtaildocs_urls

from revolv.base import views as base_views

urlpatterns = patterns(
    '',
    (r'^ckeditor/', include('ckeditor.urls')),  # for assets for the ckedit widget, etc
    url(r'^facebook/', include('django_facebook.urls')),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^$', base_views.HomePageView.as_view(), name='home'),
    url(r'^project/', include('revolv.project.urls', namespace='project')),
    url(r'^my-portfolio/$', base_views.DashboardRedirect.as_view(), name='dashboard'),
    url(r'^my-portfolio/categories/$', base_views.CategoryPreferenceSetterView.as_view(), name='dashboard_category_setter'),
    url(r'^my-portfolio/admin/', include('revolv.administrator.urls', namespace='administrator')),
    url(r'^my-portfolio/ambassador/', include('revolv.ambassador.urls', namespace='ambassador')),
    url(r'^my-portfolio/donor/', include('revolv.donor.urls', namespace='donor')),

    url(r'^what-we-do/projects/', base_views.ProjectListView.as_view(), name='projects_list'),
    url(r'^signin/$', base_views.SignInView.as_view(), name='signin'),
    url(r'^login/$', base_views.LoginView.as_view(), name='login'),
    url(r'^signup/$', base_views.SignupView.as_view(), name='signup'),
    url(r'^logout/$', base_views.LogoutView.as_view(), name='logout'),
    url(r'^unsubscribe/(?P<action>\w+)/$', 'revolv.base.views.unsubscribe', name='unsubscribe'),
    url(r'^my_social_account/$', 'revolv.base.views.social_connection', name='social-connection'),
    url(r'^social_connect_failed/$', 'revolv.base.views.social_exception', name='social-exception'),

    url(r'^password_reset/$', base_views.password_reset_initial, name="password_reset"),
    url(r'^password_reset/done/$', base_views.password_reset_done, name="password_reset_done"),
    url(r'^password_reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$$', base_views.password_reset_confirm, name="password_reset_confirm"),
    url(r'^password_reset/complete/$', base_views.password_reset_complete, name="password_reset_complete"),
    url(r'^password_change/$', base_views.password_change, name="password_change"),

    # wagtail urls, see http://wagtail.readthedocs.org/en/v1.0b2/howto/settings.html
    # note: we're not including the search module for public users, so we don't define it here
    url(r'^cms/', include(wagtailadmin_urls)),
    url(r'^documents/', include(wagtaildocs_urls)),
    url(r'social/', include('social.apps.django_app.urls', namespace='social')),
    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's serving mechanism

    url(r'', include(wagtail_urls)),

) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

revolv/project/models.py
import datetime
from itertools import chain

from ckeditor.fields import RichTextField
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models import Q, Sum
from imagekit.models import ImageSpecField, ProcessedImageField
from imagekit.processors import ResizeToFill
from revolv.base.models import RevolvUserProfile
from revolv.lib.utils import ImportProxy
from revolv.payments.models import Payment, PaymentType
from revolv.project.stats import KilowattStatsAggregator


class ProjectManager(models.Manager):
    """
    Manager for running custom operations on the Projects.
    """

    def get_featured(self, num_projects, queryset=None):
        """ Get num_projects amount of active projects. If we don't have
        enough active projects, then we retrieve completed projects. This
        function may return fewer projects than requested if not enough exist.

        :num_projects: Number of projects to be retrieved
        :queryset: The queryset in which to search for projects
        :return: A list of featured project objects
        """
        if queryset is None:
            queryset = super(ProjectManager, self).get_queryset()
        featured_projects = queryset.filter(
            project_status=Project.ACTIVE).order_by(
            'end_date')[:num_projects]
        if featured_projects.count() < num_projects:
            num_completed_needed = num_projects - featured_projects.count()
            completed_projects = queryset.filter(
                project_status=Project.COMPLETED).order_by(
                'end_date')[:num_completed_needed]
            return list(chain(featured_projects, completed_projects))
        else:
            return featured_projects

    def get_completed(self, queryset=None):
        """ Gets all the projects that have been completed funding.

        :queryset: The queryset in which to search for projects
        :return: A list of completed project objects
        """
        if queryset is None:
            queryset = super(ProjectManager, self).get_queryset()
        completed_projects = queryset.filter(
            project_status=Project.COMPLETED
        ).order_by('end_date')
        return completed_projects

    def get_active(self, queryset=None):
        """ Gets all the projects that have been active to go into funding.

        :queryset: The queryset in which to search for projects
        :return: A list of active project objects
        """
        if queryset is None:
            queryset = super(ProjectManager, self).get_queryset()
        active_projects = queryset.filter(
            project_status=Project.ACTIVE
        ).order_by('end_date')
        return active_projects

    def get_proposed(self, queryset=None):
        """ Gets all the projects that are currently in review (proposed).

        :queryset: The queryset in which to search for projects
        :return: A list of in review project objects
        """
        if queryset is None:
            queryset = super(ProjectManager, self).get_queryset()
        proposed_projects = queryset.filter(
            project_status=Project.PROPOSED
        ).order_by('updated_at')
        return proposed_projects

    def get_drafted(self, queryset=None):
        """ Get all the projects that are drafted in the queryset.

        :queryset: The queryset in which to search for projects
        :return: A list of in review project objects
        """
        if queryset is None:
            queryset = super(ProjectManager, self).get_queryset()
        drafted_projects = queryset.filter(
            project_status=Project.DRAFTED
        ).order_by('updated_at')
        return drafted_projects

    def get_staged(self, queryset=None):
        """ Get all the projects that are staged in the queryset.

        :queryset: The queryset in which to search for projects
        :return: A list of in review project objects
        """
        if queryset is None:
            queryset = super(ProjectManager, self).get_queryset()
        staged_projects = queryset.filter(
            project_status=Project.STAGED
        ).order_by('updated_at')
        return staged_projects

    def statistics(self, queryset=None):
        """
        Return a revolv.project.stats.KilowattStatsAggregator to
        aggregate statistics about the impact of the given queryset of
        projects.
        """
        if queryset is None:
            queryset = super(ProjectManager, self).get_queryset()
        return KilowattStatsAggregator.from_project_queryset(queryset)

    def owned_projects(self, user_profile):
        """ Get all projects owned by a RevolvUserProfile.

        :user: The user of interest
        :return: A list of projects for which user's RevolvUserProfile
        is the ambassador or creator.
        """
        return Project.objects.filter(Q(ambassador=user_profile) | Q(created_by_user=user_profile))

    def donated_projects(self, user_profile):
        """
        :return: Projects to which this RevolvUserProfile has donated
        """
        return user_profile.project_set.all()

    def create_from_form(self, form, creator):
        """ Creates project from form and sets created_by_user to a RevolvUserProfile.

        :form: The form
        :creator: The RevolvUserProfile of the creator of the project
        :return: Project created and saved
        """
        project = form.save(commit=False)
        project.created_by_user = creator
        project.save()
        return project

    def get_eligible_projects_for_reinvestment(self, queryset=None):
        """
        :return list(queryset) of eligible project to receive reinvestement
        """
        return self.get_active(queryset).filter(monthly_reinvestment_cap__gt=0.0)

    def get_completed_unpaid_off_projects(self, queryset=None):
        """
        :return list(queryset) of completes project which do monthly repayment.
        """
        return self.get_completed(queryset).filter(is_paid_off=True)


class Project(models.Model):
    """
    Project model. Stores basic metadata, information about the project,
    donations, energy impact, goals, and info about the organization.

    Note about project statuses: there are five kinds of statuses that a
    project can have, and we show projects to different users in different
    ways based on their status.

    When an ambassador or admin first creates a project, it becomes DRAFTED,
    which means that it's a draft and can be edited, but is not in a complete
    state yet (description may need editing, etc). Eventualy the ambassador
    can propose the project for review from the admins, at which time it becomes
    PROPOSED. A proposed project is viewable by admins in their dashboard, as
    well as by the ambassadors that created it.

    When an admin approves a project, it becomes STAGED, which means it is ready
    to go but is not active yet, and as such is not viewable by the public. Staged
    projects are also visible to all admins in their dashboards. When it's time
    for the project to go live and start accepting donations, the admin can mark
    it as ACTIVE, which means it will actually be public and people can donate to
    it. When a project is done, the admin can mark it as COMPLETED, at which point
    it will stop accepting donations and start using repayments.
    """
    ACTIVE = 'AC'
    STAGED = 'ST'
    PROPOSED = 'PR'
    COMPLETED = 'CO'
    DRAFTED = 'DR'
    PROJECT_STATUS_CHOICES = (
        (ACTIVE, 'Active'),
        (STAGED, 'Staged'),
        (PROPOSED, 'Proposed'),
        (COMPLETED, 'Completed'),
        (DRAFTED, 'Drafted'),
    )
    LESS_THAN_ONE_DAY_LEFT_STATEMENT = "only hours left"
    NO_DAYS_LEFT_STATEMENT = "deadline reached"

    funding_goal = models.DecimalField(
        max_digits=15,
        decimal_places=2,
        help_text='How much do you aim to raise for this project?'
    )
    title = models.CharField(
        max_length=255,
        help_text='How would you like to title this project?'
    )
    tagline = models.CharField(
        max_length=100,
        null=True,
        blank=False,
        help_text='Select a short tag line that describes this project. (No more than 100 characters.)'
    )
    video_url = models.URLField(
        'Video URL',
        max_length=255,
        blank=False,
        help_text='Link to a Youtube video about the project or community.',
    )
    # power output of array in kilowatts
    impact_power = models.FloatField(
        'Expected Killowatt Output',
        help_text='What is the expected output in killowatts of the proposed solar array?'
    )
    # solar log graphics url
    solar_url = models.URLField(
        'Solar Log Graphics URL',
        max_length=255,
        blank=True,
        help_text='This can be found by going to http://home.solarlog-web.net/, going to the \
        solar log profile for your site, and clicking on the Graphics sub-page. Copy and paste \
        the URL in the address bar into here.'
    )
    location = models.CharField(
        'Organization Address',
        max_length=255,
        help_text='What is the address of the organization where the solar panels will be installed?'
    )
    # latitude and longitude of the organization location
    location_latitude = models.DecimalField(
        max_digits=17,
        decimal_places=14,
        default=0.0
    )
    location_longitude = models.DecimalField(
        max_digits=17,
        decimal_places=14,
        default=0.0
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    end_date = models.DateField(
        help_text='When will this crowdfunding project end?'
    )
    # the start date of a project is whenever the project becomes live,
    # so we have to set it dynamically. Accordingly, the start_date
    # field is blank=True.
    start_date = models.DateField(
        blank=True,

revolv/administrator/forms.py
from django import forms
from revolv.payments.models import AdminAdjustment
from revolv.project.models import Project
from django.forms.models import modelform_factory


AdjustmentForm = modelform_factory(AdminAdjustment)

revolv/administrator/views.py
import csv

from django.http import HttpResponse
from django.views.generic import TemplateView
from revolv.base.models import RevolvUserProfile
from revolv.base.users import UserDataMixin
from revolv.base.utils import ProjectGroup
from revolv.base.views import BaseStaffDashboardView
from revolv.project.models import Project


class AdministratorDashboardView(BaseStaffDashboardView):
    """
    Basic view for the Administrator dashboard. Shows the list of projects that this
    ambassador owns. Also, shows drafted projects.
    """
    template_name = 'base/dashboard.html'
    role = "admin"

    def get_context_data(self, **kwargs):
        context = super(AdministratorDashboardView, self).get_context_data(**kwargs)

        context["project_dict"][ProjectGroup('Drafted Projects', "drafted")] = Project.objects.get_drafted()
        return context


class AdministratorEmailView(UserDataMixin, TemplateView):
    """View for the list of newsletter subscribers for the dashboard.
    """
    template_name = 'administrator/email.html'

    def get_context_data(self, **kwargs):
        context = super(AdministratorEmailView, self).get_context_data(**kwargs)

        user_profiles = RevolvUserProfile.objects.get_subscribed_to_newsletter()
        user_emails = list(user_profiles.values_list("user__email", flat=True))

        context['subscribed_user_emails'] = user_emails
        return context


def admin_email_csv_download(request):
    """View for downloading the list of newsletter subscribers as a csv file.
    Accessed via AdministratorEmailView.
    """
    # Create the HttpResponse object with the appropriate CSV header.
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="emails.csv"'

    users_subscribed = RevolvUserProfile.objects.get_subscribed_to_newsletter()
    newsletter_rows = [(u.user.email, u.user.first_name, u.user.last_name, u.user.date_joined) for u in users_subscribed]

    writer = csv.writer(response)
    writer.writerow(['Email', 'FirstName', 'LastName', 'DateJoined'])
    writer.writerows(newsletter_rows)

    return response

revolv/revolv_cms/views.py
from django.shortcuts import render

# Create your views here.

revolv/templates/project/edit_project.html
{% extends "base/base.html" %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block head %}
<link rel="stylesheet" href="{% static "typeahead/typeahead.css" %}" />
<link rel="stylesheet" href="{% static "chosen/chosen.css" %}" />
<link rel="stylesheet" href="{% static 'dist/css/pages/project-edit/index.css' %}" />
<link href='//fonts.googleapis.com/css?family=Lato:300,500,800' rel='stylesheet' type='text/css'>
<style type="text/css">
    #map-canvas { width: 100%; height: 300px; margin-bottom: 20px; padding: 0;}
    #map-canvas img {max-width: none;}
</style>

{% endblock %}

{% block title %}{% if project.id %}Edit{% else %}Create{% endif %} Project | {% endblock %}

{% block nav %}
  {% include "base/partials/project-nav.html" %}
{% endblock %}

{% block body %}
<div class="contents after-header edit-project">
  <div class="container">
    <div class="row form-section">
        <div class="large-12 columns">
            <form method="POST" enctype="multipart/form-data" id="project_form">
                  {% csrf_token %}
                  {{ form.media }}
                  {% for error in form.non_field_errors %}
                <div data-alert class="alert-box alert">
                    {{ error }}
                    <a href="#" class="close">&times;</a>
                  </div>
                {% endfor %}

                <div class="row project-overview section">
                    <p class="section-title">Project Overview</p>
                    <div class="medium-6 small-12 columns">
                        {% include "base/partials/tooltip_formfield.html" with field=form.title %}
                        {% include "base/partials/tooltip_formfield.html" with field=form.tagline %}
                        <span>Categories</span>
                        {{ form.categories_select|add_class:"chosen-select" }}
                        {% for error in form.categories_select.errors %}
                            <small class="error">{{ error }}</small>
                        {% endfor %}
                    </div>

                    <div class="medium-6 small-12 columns">
                        {% include "base/partials/tooltip_formfield.html" with field=form.funding_goal %}
                        {% include "base/partials/tooltip_formfield.html" with field=form.impact_power %}
                        {% include "base/partials/tooltip_formfield.html" with field=form.end_date %}
                    </div>

                    <div class="medium-12 small-12 columns">
                        {% include "base/partials/tooltip_formfield.html" with field=form.video_url %}
                        {% include "base/partials/tooltip_formfield.html" with field=form.cover_photo %}
                        {% include "base/partials/tooltip_formfield.html" with field=form.description %}
                    </div>
                </div>

                <div class="row donation-levels section">
                    <p class="section-title donation-level-container">Donation Levels</p>
                    {{ donation_level_formset.management_form }}
                    <script type="text/javascript">
                        window.DONATION_LEVEL_COUNT = {{ donation_level_formset|length }};
                        window.EXTRA = 1;
                    </script>
                    {% for donation_level_form in donation_level_formset %}
                        <div class="donation-level-box donation-level-{{ forloop.counter0 }}">
                            <div class="small-4 columns">
                                {% include "base/partials/tooltip_formfield.html" with field=donation_level_form.amount %}
                                {% include "base/partials/tooltip_formfield.html" with field=donation_level_form.DELETE %}
                            </div>
                            <div class="small-8 columns">
                                {% include "base/partials/tooltip_formfield.html" with field=donation_level_form.description %}
                            </div>
                            {% for hidden in donation_level_form.hidden_fields %}
                                {{ hidden }}
                            {% endfor %}
                        </div>
                    {% endfor %}
                </div>

                <!-- THIS DOES NOT EXIST -->
                <!-- <div class="row add-button">Add a new donation level</div> -->

                <div class="row organization-overview section">
                    <p class="section-title">Organization Overview</p>
                    <div class="medium-12 small-12 columns">
                        {% include "base/partials/tooltip_formfield.html" with field=form.org_name %}
                    </div>
                    <div class="medium-6 small-12 columns">
                        {% include "base/partials/tooltip_formfield.html" with field=form.org_start_date %}
                    </div>
                    <div class="medium-6 small-12 columns">
                        {% include "base/partials/tooltip_formfield.html" with field=form.people_affected %}                </div>
                    <div class="medium-12 small-12 columns">
                        {% include "base/partials/tooltip_formfield.html" with field=form.location %}
                        <div id="map-canvas"></div>
                        {% include "base/partials/tooltip_formfield.html" with field=form.org_about %}
                    </div>
                </div>
                <div class="hide">
                    {% include "base/partials/tooltip_formfield.html" with field=form.location_latitude %}
                    {% include "base/partials/tooltip_formfield.html" with field=form.location_longitude %}
                    {% include "base/partials/tooltip_formfield.html" with field=form.extra %}
                </div>
                <button class="large right save-button" id="save_project" type="submit">Save</button>
            </form>
        </div>
    </div>
  </div>
</div>

{% endblock %}

{% block javascripts %}
<!-- Initializes the Google Map / Location Selection Typeahead -->
<script type="text/javascript"
    src="//maps.googleapis.com/maps/api/js?key={{GOOGLEMAPS_API_KEY}}&libraries=places">
</script>
<script src="{% static 'typeahead/typeahead.bundle.js' %}"></script>
<script src="{% static 'typeahead/typeahead-addresspicker.js' %}"></script>
<script type="text/javascript">
    // gets the start location of the map
    {% if project.location_latitude %}
        var latitude = {{project.location_latitude}};
    {% else %}
        var latitude = 37.7699298;
    {% endif %}

    {% if project.location_longitude %}
        var longitude = {{project.location_longitude}};
    {% else %}
        var longitude = -122.4469157;
    {% endif %}
    var startLocation = new google.maps.LatLng(latitude, longitude);
    // instantiate the addressPicker suggestion engine (based on bloodhound)
    // https://github.com/sgruhier/typeahead-addresspicker
    var addressPicker = new AddressPicker({
        map: {
            center: startLocation,
            id: '#map-canvas',
            displayMarker: true,
            zoom: 18
        },
        marker: {
            position: startLocation,
            visible: true,
            draggable: false
        },
        zoomForLocation: 18,
        draggable: false,
        reverseGeocoding: true,
        utocompleteService: {
            componentRestrictions: {
                country: 'US'
            }
        }
    });
    // instantiate the typeahead UI
    $('#id_location').typeahead(null, {
        displayKey: 'description',
        source: addressPicker.ttAdapter()
    });
    // add click listeners
    addressPicker.bindDefaultTypeaheadEvent($('#id_location'))
    $(addressPicker).on('addresspicker:selected', function (event, result) {
        $('#id_location_latitude').val(result.lat());
        $('#id_location_longitude').val(result.lng());
    });

    $("#project_form").on('submit', function(e) {
        if (!$('#id_location_latitude').val() || !$('#id_location_longitude').val()) {
            toastr.options.positionClass = "toast-bottom-right";
            toastr.error("Please enter a valid address");
            e.preventDefault();
            return false;
        }
    });
</script>
<!-- Initializes the category selection tool -->
<script src="{% static 'chosen/chosen.jquery.js' %}"></script>
<script type="text/javascript">
    $("#id_extra").val(1);

    $('<div class="project-edit-spacer"></div>').insertBefore("#cover_photo-clear_id");
    // window.PROJECT_ID = {{ project.id }};
</script>
<script type="text/javascript">
    $(".chosen-select").chosen();
</script>

{% endblock %}

revolv/templates/project/edit_project_update.html
{% extends "base/base.html" %}
{% load staticfiles %}

{% block head %}
<link rel="stylesheet" href="{% static 'dist/css/pages/project-edit/index.css' %}" />
<link href='//fonts.googleapis.com/css?family=Lato:300,500,800' rel='stylesheet' type='text/css'>
{% endblock %}

{% block title %}Post Project Updates | {% endblock %}

{% block body %}

<div class='row header-container'>
    <div class='medium-4 columns'>
        <div class="blue-bar"></div>
    </div>
    <div class='medium-4 columns'>
        <h1 class="header">Post Project Update</h1>
    </div>
    <div class='medium-4 columns'>
        <div class="blue-bar"></div>
    </div>
</div>
<div class="row form-section">
    <div class="large-12 columns">
        <form id="project_update_form" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.media }}
            {% for error in form.non_field_errors %}
            <div data-alert class="alert-box alert">
                {{ error }}
                <a href="#" class="close">&times;</a>
            </div>
            {% endfor %}
            <div class="row">
                <div class="medium-12 columns">
                    {% include "base/partials/tooltip_formfield.html" with field=form.update_text %}
                </div>
            </div>
            <button class="large right save-button" id="save_project" type="submit">Save</button>
        </form>
    </div>
</div>

{% endblock %}

revolv/templates/project/project_donate_erorr.html
{% extends "base/base.html" %}
{% load staticfiles %}

{% block title %}Payment Error | {% endblock %}

{% block head %}
<link href='http://fonts.googleapis.com/css?family=Lato:300,500,800' rel='stylesheet' type='text/css'>
{% endblock %}

{% block body %}
<div class="row container">
	<h1 class="title">There was an error processing your payment</h1>
	Return to <a href="{{ project.get_absolute_url }}">{{ project.title }}</a>
</div>
{% endblock %}

revolv/templates/project/project_donate_error.html
{% extends "base/base.html" %}
{% load staticfiles %}

{% block title %}Payment Error | {% endblock %}

{% block head %}
<link href='http://fonts.googleapis.com/css?family=Lato:300,500,800' rel='stylesheet' type='text/css'>
{% endblock %}

{% block body %}
<div class="row container">
	<h1 class="title">There was an error processing your payment</h1>
	Return to <a href="{{ project.get_absolute_url }}">{{ project.title }}</a>
</div>
{% endblock %}